name: Deploy to Staging
on:
  pull_request:
    types:
      - closed
    branches:
      - staging

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: self-hosted  # Run on your self-hosted runner
    # Or, if you gave the runner a specific label:
    # runs-on: [self-hosted, staging-runner]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # important to get all history for rsync

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          name: deploy_key # optional

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "mkdir -p ${{ secrets.DEPLOY_PATH }}"
          rsync -avz --delete ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.DEPLOY_PATH }}

      # Optional: Add steps to run build scripts, migrations, etc.
      # Example:
      - name: Run Build Script
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.DEPLOY_PATH }} && npm install && npm run build"
