name: Release Frontend

on:
  push:
    branches:
      - master
    paths:
      - 'front/**'
      - '.github/workflows/front-release.yml'
  pull_request:
    branches:
      - master
    paths:
      - 'front/**'
      - '.github/workflows/front-release.yml'

permissions:
  contents: write
  pull-requests: write

jobs:
  release-front:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run release-please
        uses: googleapis/release-please-action@v4
        with:
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
